import { PoolClient } from 'pg';
import { SeedFn, SeedSize } from '../../src/utils/seed-runner.utils';

interface SeedQuestion {
  skill_area: string;
  topic: string;
  difficulty: number;
  question_text: string;
  options: string[];
  correct_answer: string;
  explanation: string;
}

const QUESTIONS: SeedQuestion[] = [
  // --- Skill Area 1: TypeScript / JavaScript (20 questions, diff 1-10) ---
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Basics',
    difficulty: 1,
    question_text: 'Which JavaScript keyword is used to declare a variable that cannot be reassigned?',
    options: ['var', 'let', 'const', 'static'],
    correct_answer: 'const',
    explanation: 'const declarations create block-scoped variables that cannot be reassigned.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Types',
    difficulty: 2,
    question_text: 'What is the type of NaN in JavaScript when using typeof NaN?',
    options: ['number', 'nan', 'undefined', 'object'],
    correct_answer: 'number',
    explanation: 'In JavaScript IEEE 754 floating point standard, NaN has type number.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Equality',
    difficulty: 3,
    question_text: 'What does the strict equality operator (===) compare in JavaScript?',
    options: ['Value only with type coercion', 'Both value and data type without coercion', 'Memory address only', 'Object prototype'],
    correct_answer: 'Both value and data type without coercion',
    explanation: '=== checks both type and value without performing automatic type conversion.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Arrays',
    difficulty: 4,
    question_text: 'Which Array method produces a new array by applying a callback to every element?',
    options: ['forEach', 'filter', 'map', 'reduce'],
    correct_answer: 'map',
    explanation: 'Array.prototype.map() transforms each element and returns a new array of the same length.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Async',
    difficulty: 5,
    question_text: 'What state is a Promise in right after instantiation before resolve or reject is called?',
    options: ['fulfilled', 'pending', 'settled', 'resolved'],
    correct_answer: 'pending',
    explanation: 'A Promise starts in pending state and transitions to either fulfilled or rejected.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Closures',
    difficulty: 6,
    question_text: 'What is a closure in JavaScript?',
    options: ['A function bundled with references to its surrounding lexical environment', 'A method to close browser tabs', 'A syntax error in nested functions', 'A private class field'],
    correct_answer: 'A function bundled with references to its surrounding lexical environment',
    explanation: 'A closure gives an inner function access to an outer function scope even after the outer function has executed.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'TypeScript Types',
    difficulty: 7,
    question_text: 'What is the difference between "unknown" and "any" in TypeScript?',
    options: ['unknown is typesafe and requires type narrowing before operations; any disables type checking', 'any is typesafe while unknown disables all checks', 'They are completely identical', 'unknown can only hold null or undefined'],
    correct_answer: 'unknown is typesafe and requires type narrowing before operations; any disables type checking',
    explanation: 'unknown is the type-safe counterpart of any. Anything is assignable to unknown, but unknown is not assignable to anything else without narrowing.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Event Loop',
    difficulty: 8,
    question_text: 'Which queue has higher priority in the JavaScript runtime event loop: microtasks or macrotasks?',
    options: ['Macrotasks (setTimeout, setInterval)', 'Microtasks (Promise.then, queueMicrotask)', 'They alternate in round-robin', 'Depends on CPU clock'],
    correct_answer: 'Microtasks (Promise.then, queueMicrotask)',
    explanation: 'All microtasks in the microtask queue are drained before the next macrotask is processed from the task queue.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Generics',
    difficulty: 9,
    question_text: 'In TypeScript, what does the keyof operator do?',
    options: ['Produces a string or numeric literal union of an object type keys', 'Returns an array of runtime keys', 'Generates a random key', 'Validates cryptographic keys'],
    correct_answer: 'Produces a string or numeric literal union of an object type keys',
    explanation: 'keyof T produces a union of literal types representing all valid keys of T.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Advanced TS',
    difficulty: 10,
    question_text: 'How does conditional type distributive behavior work over naked type parameters in TypeScript?',
    options: ['T extends U ? X : Y distributes across union types T (e.g. (A|B) -> (A extends U ? X : Y) | (B extends U ? X : Y))', 'It evaluates to never for all unions', 'It causes a compiler error', 'It merges all union branches into any'],
    correct_answer: 'T extends U ? X : Y distributes across union types T (e.g. (A|B) -> (A extends U ? X : Y) | (B extends U ? X : Y))',
    explanation: 'When conditional types act on a generic parameter that is an unresolved union, they distribute over the union members automatically.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Prototypes',
    difficulty: 5,
    question_text: 'What object sits at the top of the JavaScript prototype chain?',
    options: ['Function.prototype', 'Object.prototype', 'null', 'Array.prototype'],
    correct_answer: 'null',
    explanation: 'The prototype chain ends at Object.prototype whose prototype is null.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Scope',
    difficulty: 3,
    question_text: 'Which declaration is hoisted with its assignment in JavaScript?',
    options: ['Function declaration', 'var variable', 'let variable', 'const variable'],
    correct_answer: 'Function declaration',
    explanation: 'Function declarations are hoisted completely with their definitions, unlike var which is hoisted as undefined.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Decorators',
    difficulty: 8,
    question_text: 'What are Stage 3 TC39 Decorators in modern TypeScript/JavaScript?',
    options: ['Functions that modify classes, methods, accessors, or fields at declaration time', 'CSS stylers for HTML nodes', 'Webpack plugins', 'React hooks'],
    correct_answer: 'Functions that modify classes, methods, accessors, or fields at declaration time',
    explanation: 'Decorators are functions applied to classes and class members to observe, modify, or replace definitions.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Symbols',
    difficulty: 6,
    question_text: 'What is a primary characteristic of JavaScript Symbol values?',
    options: ['They are guaranteed to be unique and immutable primitive values', 'They are mutable objects', 'They automatically serialize to JSON', 'They equal their string names'],
    correct_answer: 'They are guaranteed to be unique and immutable primitive values',
    explanation: 'Symbols are primitive values often used as non-enumerable unique object property keys.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Modules',
    difficulty: 4,
    question_text: 'Are ES Module imports statically analyzed or dynamically evaluated by default?',
    options: ['Statically analyzed at compile/parse time', 'Dynamically evaluated at runtime', 'Resolved via eval()', 'Lazy loaded on click'],
    correct_answer: 'Statically analyzed at compile/parse time',
    explanation: 'Static import statements are hoisted and analyzed before module evaluation, allowing dead-code tree shaking.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Utility Types',
    difficulty: 7,
    question_text: 'What does the Pick<T, K> utility type construct in TypeScript?',
    options: ['A type by picking the set of properties K from T', 'A type excluding properties K from T', 'A tuple of all properties', 'A deep readonly clone'],
    correct_answer: 'A type by picking the set of properties K from T',
    explanation: 'Pick<T, K> creates a new type containing only the keys specified in union K.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Memory',
    difficulty: 9,
    question_text: 'How does WeakMap differ from Map regarding garbage collection in V8?',
    options: ['WeakMap holds weak references to key objects allowing them to be garbage collected when no other references exist', 'WeakMap has weaker cryptographic security', 'WeakMap never gets garbage collected', 'WeakMap allows primitive keys only'],
    correct_answer: 'WeakMap holds weak references to key objects allowing them to be garbage collected when no other references exist',
    explanation: 'Keys of WeakMap must be objects and do not prevent garbage collection of those objects.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Async Iteration',
    difficulty: 8,
    question_text: 'Which protocol method must an object implement to be consumed by `for await (... of ...)`?',
    options: ['[Symbol.asyncIterator]()', '[Symbol.iterator]()', 'nextAsync()', 'stream()'],
    correct_answer: '[Symbol.asyncIterator]()',
    explanation: 'The async iterable protocol requires the [Symbol.asyncIterator] method returning an async iterator with next() returning a promise.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Error Handling',
    difficulty: 2,
    question_text: 'Which block in a try-catch-finally statement always executes regardless of an error?',
    options: ['finally', 'catch', 'try', 'throw'],
    correct_answer: 'finally',
    explanation: 'The finally block executes whether an exception was thrown or caught.',
  },
  {
    skill_area: 'TypeScript/JavaScript',
    topic: 'Template Literals',
    difficulty: 6,
    question_text: 'What receives the raw strings array and expression arguments in tagged template literals?',
    options: ['A tag function (e.g. tag(strings, ...values))', 'The browser window', 'eval()', 'JSON.stringify()'],
    correct_answer: 'A tag function (e.g. tag(strings, ...values))',
    explanation: 'Tagged template literals call a tag function passing TemplateStringsArray followed by evaluated expressions.',
  },

  // --- Skill Area 2: Python & Data Structures (18 questions, diff 1-10) ---
  {
    skill_area: 'Python & Data Structures',
    topic: 'Basics',
    difficulty: 1,
    question_text: 'Which built-in Python data structure maintains an ordered, mutable sequence of elements?',
    options: ['list', 'tuple', 'set', 'frozenset'],
    correct_answer: 'list',
    explanation: 'Lists in Python are ordered and mutable sequences.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Mutability',
    difficulty: 2,
    question_text: 'Is a Python tuple mutable or immutable?',
    options: ['Immutable', 'Mutable', 'Mutable if defined with let', 'Mutable inside functions'],
    correct_answer: 'Immutable',
    explanation: 'Tuples cannot be altered once created in Python.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Complexity',
    difficulty: 3,
    question_text: 'What is the average time complexity for key lookup in a Python dictionary (hash table)?',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'],
    correct_answer: 'O(1)',
    explanation: 'Python dicts use open-addressing hash tables providing average O(1) constant time lookup.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Sorting',
    difficulty: 4,
    question_text: 'Which sorting algorithm is Python built-in sort() (Timsort) based on?',
    options: ['Hybrid of Merge Sort and Insertion Sort', 'Pure Quick Sort', 'Heap Sort', 'Bubble Sort'],
    correct_answer: 'Hybrid of Merge Sort and Insertion Sort',
    explanation: 'Timsort combines merge sort and insertion sort to achieve high performance on real-world partially sorted data.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Queues',
    difficulty: 5,
    question_text: 'Which data structure from the collections module provides O(1) appends and pops from both ends?',
    options: ['collections.deque', 'collections.namedtuple', 'collections.defaultdict', 'collections.Counter'],
    correct_answer: 'collections.deque',
    explanation: 'A deque (double-ended queue) guarantees O(1) operations on both ends, whereas list.pop(0) is O(n).',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Trees',
    difficulty: 6,
    question_text: 'In a Balanced Binary Search Tree with N nodes, what is the maximum height and search complexity?',
    options: ['O(log N)', 'O(N)', 'O(N^2)', 'O(1)'],
    correct_answer: 'O(log N)',
    explanation: 'Balanced BSTs (AVL, Red-Black) maintain height proportional to log2(N), giving O(log N) search.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Generators',
    difficulty: 7,
    question_text: 'What keyword turns a Python function into a generator returning an iterator object?',
    options: ['yield', 'return', 'async', 'iter'],
    correct_answer: 'yield',
    explanation: 'Using yield pauses function execution and produces values lazily one at a time.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Graphs',
    difficulty: 8,
    question_text: 'Which graph algorithm computes the shortest paths from a single source vertex to all others with non-negative weights?',
    options: ['Dijkstra algorithm', 'Kruskal algorithm', 'Floyd-Warshall algorithm', 'Depth First Search'],
    correct_answer: 'Dijkstra algorithm',
    explanation: 'Dijkstras algorithm uses a min-priority queue to find single-source shortest paths in O((V + E) log V).',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'GIL & Concurrency',
    difficulty: 9,
    question_text: 'What is the function of the Global Interpreter Lock (GIL) in CPython?',
    options: ['Mutex that protects access to Python objects preventing multiple native threads from executing Python bytecodes simultaneously', 'A database lock on SQLite', 'A memory encryption mechanism', 'A network socket limiter'],
    correct_answer: 'Mutex that protects access to Python objects preventing multiple native threads from executing Python bytecodes simultaneously',
    explanation: 'The GIL prevents race conditions in CPythons reference counting memory manager by serializing bytecode execution.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Advanced Heaps',
    difficulty: 10,
    question_text: 'What is the amortized time complexity of decrease-key operation in a Fibonacci Heap vs Binary Heap?',
    options: ['O(1) amortized vs O(log n)', 'O(log n) vs O(1)', 'O(n) vs O(log n)', 'O(1) vs O(1)'],
    correct_answer: 'O(1) amortized vs O(log n)',
    explanation: 'Fibonacci heaps achieve O(1) amortized time for decrease-key and insert, making them optimal for theoretical graph algorithms.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Decorators',
    difficulty: 5,
    question_text: 'What decorator from functools preserves the original function name and docstring when wrapping?',
    options: ['@functools.wraps', '@functools.lru_cache', '@functools.total_ordering', '@functools.partial'],
    correct_answer: '@functools.wraps',
    explanation: '@wraps copies metadata like __name__ and __doc__ from the target function to the decorator wrapper.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Hash Maps',
    difficulty: 6,
    question_text: 'What happens when two distinct keys produce the exact same hash in Python dict?',
    options: ['Hash collision resolved via open addressing with quadratic/perturbation probing', 'The second key overwrites the first silently', 'An exception is raised', 'Python creates a linked list chain'],
    correct_answer: 'Hash collision resolved via open addressing with quadratic/perturbation probing',
    explanation: 'CPython uses open addressing with a recurrence perturbation sequence to probe empty slots on collisions.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Memory',
    difficulty: 7,
    question_text: 'What garbage collection strategy does CPython use primarily, complemented by generational cycle detection?',
    options: ['Reference counting', 'Mark and sweep only', 'Copying collector', 'Stop-the-world compaction'],
    correct_answer: 'Reference counting',
    explanation: 'CPython deallocates objects immediately when their reference count drops to zero, using a generational GC to find cyclic isolates.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Dynamic Programming',
    difficulty: 8,
    question_text: 'What two essential properties must a problem exhibit to be solvable with Dynamic Programming?',
    options: ['Optimal substructure and overlapping subproblems', 'Linear independence and greedy choice', 'Convexity and differentiability', 'Binary searchability and sorting'],
    correct_answer: 'Optimal substructure and overlapping subproblems',
    explanation: 'DP solves problems whose global optimum incorporates subproblem optima and whose subproblems repeat frequently.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Metaclasses',
    difficulty: 9,
    question_text: 'What is a metaclass in Python?',
    options: ['A class whose instances are classes (the blueprint of a class)', 'A class that inherits from multiple parents', 'A static abstract class', 'A C-extension module'],
    correct_answer: 'A class whose instances are classes (the blueprint of a class)',
    explanation: 'type is the default metaclass in Python; custom metaclasses customize class construction and registration.',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Tries',
    difficulty: 7,
    question_text: 'Which prefix tree data structure is optimal for autocomplete search over a dictionary of words?',
    options: ['Trie (Prefix Tree)', 'Binary Heap', 'Red-Black Tree', 'Disjoint Set (Union-Find)'],
    correct_answer: 'Trie (Prefix Tree)',
    explanation: 'A Trie allows lookup, prefix matching, and insertion proportional to the length of the string O(L).',
  },
  {
    skill_area: 'Python & Data Structures',
    topic: 'Context Managers',
    difficulty: 4,
    question_text: 'Which two dunder methods must a Python class implement to support the `with` statement?',
    options: ['__enter__ and __exit__', '__open__ and __close__', '__start__ and __stop__', '__init__ and __del__'],
    correct_answer: '__enter__ and __exit__',
    explanation: 'The context management protocol relies on __enter__() returning the resource and __exit__() handling cleanup/exceptions.',
  },

  // --- Skill Area 3: System Design & Databases (17 questions, diff 1-10) ---
  {
    skill_area: 'System Design & Databases',
    topic: 'ACID',
    difficulty: 1,
    question_text: 'What does the "A" in the ACID properties of database transactions stand for?',
    options: ['Atomicity', 'Availability', 'Accuracy', 'Authentication'],
    correct_answer: 'Atomicity',
    explanation: 'Atomicity guarantees that all operations in a transaction succeed together or are rolled back completely.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Indexing',
    difficulty: 2,
    question_text: 'What is the primary purpose of creating an index on a PostgreSQL table column?',
    options: ['Accelerate query SELECT filter lookups at the cost of slower INSERT/UPDATE writes', 'Enforce user passwords', 'Compress disk storage', 'Automatically backup data'],
    correct_answer: 'Accelerate query SELECT filter lookups at the cost of slower INSERT/UPDATE writes',
    explanation: 'Indexes provide fast B-Tree lookups for search queries but add overhead to write operations.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Foreign Keys',
    difficulty: 3,
    question_text: 'What does the clause "ON DELETE CASCADE" specify in a foreign key constraint?',
    options: ['Deleting the referenced parent row automatically deletes all corresponding child rows', 'Prevents deletion of parent rows', 'Sets foreign key values to NULL', 'Logs deletion to a shadow table'],
    correct_answer: 'Deleting the referenced parent row automatically deletes all corresponding child rows',
    explanation: 'CASCADE propagates deletions from the referenced table to all referencing rows.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'CAP Theorem',
    difficulty: 4,
    question_text: 'According to the CAP Theorem, which three properties can a distributed data store not simultaneously guarantee in network partitions?',
    options: ['Consistency, Availability, and Partition Tolerance', 'Concurrency, Accuracy, and Performance', 'Caching, Authentication, and Persistence', 'Capacity, Authorization, and Privacy'],
    correct_answer: 'Consistency, Availability, and Partition Tolerance',
    explanation: 'When network partitions occur, a distributed system must choose between returning consistent data or remaining available.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Caching',
    difficulty: 5,
    question_text: 'What is the Cache-Aside (Lazy Loading) pattern in system design?',
    options: ['Application reads from cache; on miss, reads from database, updates cache, and returns data', 'Cache writes directly to DB asynchronously', 'Database calls cache on trigger', 'Cache evicts oldest key on every hit'],
    correct_answer: 'Application reads from cache; on miss, reads from database, updates cache, and returns data',
    explanation: 'Cache-aside places the cache responsibility on the application layer to populate missing data.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Sharding',
    difficulty: 6,
    question_text: 'What is database horizontal partitioning (sharding)?',
    options: ['Splitting rows of a table across multiple independent database instances by a shard key', 'Splitting columns into separate tables', 'Adding more RAM to a single server', 'Running read replicas in one cluster'],
    correct_answer: 'Splitting rows of a table across multiple independent database instances by a shard key',
    explanation: 'Horizontal sharding divides table rows among multiple database servers to scale write throughput and storage.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Isolation Levels',
    difficulty: 7,
    question_text: 'Which SQL transaction isolation level prevents Dirty Reads and Non-Repeatable Reads, but may permit Phantom Reads?',
    options: ['Repeatable Read', 'Read Committed', 'Read Uncommitted', 'Serializable'],
    correct_answer: 'Repeatable Read',
    explanation: 'Repeatable Read guarantees that any row read during a transaction will see the same snapshot, though new rows (phantoms) can appear in standard SQL.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Load Balancing',
    difficulty: 8,
    question_text: 'How does Consistent Hashing minimize cache invalidation when servers are added or removed?',
    options: ['Maps both servers and keys to a circular ring so rebalancing only remaps k/N keys', 'Hashes all keys to a single master node', 'Randomly assigns requests using round-robin', 'Stores an in-memory routing table on DNS'],
    correct_answer: 'Maps both servers and keys to a circular ring so rebalancing only remaps k/N keys',
    explanation: 'Consistent hashing bounds key migration to K/N on cluster resizing instead of invalidating all keys as with hash % N.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Consensus',
    difficulty: 9,
    question_text: 'What is the core role of the Raft consensus algorithm in distributed systems like etcd?',
    options: ['Ensures state machine replication and leader election across a cluster tolerating minority node failures', 'Compresses HTTP/2 streams', 'Manages DNS records', 'Encrypts TLS handshakes'],
    correct_answer: 'Ensures state machine replication and leader election across a cluster tolerating minority node failures',
    explanation: 'Raft achieves consensus via leader election, log replication, and safety invariants, providing fault tolerance for distributed state.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'MVCC',
    difficulty: 10,
    question_text: 'How does PostgreSQL Multi-Version Concurrency Control (MVCC) ensure readers do not block writers?',
    options: ['Each transaction sees a snapshot of data at a point in time; updates create new row versions with xmin/xmax metadata', 'PostgreSQL locks the entire table during updates', 'PostgreSQL uses shared CPU memory locks', 'All transactions are serialized into a single thread'],
    correct_answer: 'Each transaction sees a snapshot of data at a point in time; updates create new row versions with xmin/xmax metadata',
    explanation: 'Postgres writes new tuple versions tagged with transaction IDs (xmin/xmax), allowing readers to access valid historical snapshots without acquiring table or row locks.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Message Brokers',
    difficulty: 5,
    question_text: 'How does an event streaming log like Apache Kafka differ from a traditional message queue like RabbitMQ?',
    options: ['Kafka retains an immutable append-only distributed log where consumers manage their own offset position', 'RabbitMQ never deletes messages', 'Kafka can only process 1 message per second', 'RabbitMQ requires no memory'],
    correct_answer: 'Kafka retains an immutable append-only distributed log where consumers manage their own offset position',
    explanation: 'Kafka treats topics as durable partitioned logs where multiple consumer groups track their independent offsets.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Rate Limiting',
    difficulty: 6,
    question_text: 'Which rate-limiting algorithm permits brief bursts of traffic up to capacity while enforcing a steady long-term outflow rate?',
    options: ['Token Bucket / Leaky Bucket', 'Fixed Window Counter', 'Round Robin', 'Exponential Backoff'],
    correct_answer: 'Token Bucket / Leaky Bucket',
    explanation: 'Token bucket fills tokens at a constant rate and allows bursts as long as accumulated tokens are available.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Bloom Filters',
    difficulty: 7,
    question_text: 'What is the key probabilistic guarantee of a Bloom filter in database storage engines like RocksDB?',
    options: ['Zero false negatives (if it says an element is absent, it is definitely absent), but possible false positives', 'Zero false positives and zero false negatives', 'Guaranteed exact item count', 'Automatic item sorting'],
    correct_answer: 'Zero false negatives (if it says an element is absent, it is definitely absent), but possible false positives',
    explanation: 'Bloom filters prevent unnecessary disk seeks on SSTables because a negative lookup definitively confirms the key does not exist on disk.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Database Replication',
    difficulty: 5,
    question_text: 'What issue can arise when a client writes to a primary database and immediately reads from an asynchronous replica?',
    options: ['Replication lag causing stale read (read-your-own-writes violation)', 'Deadlock on the primary', 'Corrupted WAL files', 'Primary database shutdown'],
    correct_answer: 'Replication lag causing stale read (read-your-own-writes violation)',
    explanation: 'Asynchronous replication lag means updates take milliseconds or seconds to reach replicas, causing temporary inconsistencies.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Storage Engines',
    difficulty: 8,
    question_text: 'Why do LSM-tree storage engines (e.g. Cassandra, LevelDB) achieve higher write throughput than standard B-Trees?',
    options: ['They turn random disk writes into sequential append-only writes via in-memory MemTables and write-ahead logs (WAL)', 'They bypass the operating system kernel', 'They do not maintain indexes', 'They store data purely in volatile RAM'],
    correct_answer: 'They turn random disk writes into sequential append-only writes via in-memory MemTables and write-ahead logs (WAL)',
    explanation: 'LSM trees batch writes in memory and flush sequential SSTables to disk, minimizing expensive random disk I/O.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'API Design',
    difficulty: 3,
    question_text: 'What HTTP method is considered idempotent: PUT or POST?',
    options: ['PUT is idempotent; POST is not idempotent', 'POST is idempotent; PUT is not', 'Both are non-idempotent', 'Neither is idempotent'],
    correct_answer: 'PUT is idempotent; POST is not idempotent',
    explanation: 'Executing a PUT request multiple times produces the same state result as executing it once, whereas repeated POST creates multiple resources.',
  },
  {
    skill_area: 'System Design & Databases',
    topic: 'Two-Phase Commit',
    difficulty: 9,
    question_text: 'What is the primary vulnerability of the Two-Phase Commit (2PC) distributed transaction protocol?',
    options: ['It is a blocking protocol: if the coordinator crashes during the prepare phase, cohorts can be blocked indefinitely waiting for commit/abort', 'It cannot handle network encryption', 'It is non-atomic', 'It only works with 2 nodes'],
    correct_answer: 'It is a blocking protocol: if the coordinator crashes during the prepare phase, cohorts can be blocked indefinitely waiting for commit/abort',
    explanation: '2PC coordinator single-point-of-failure leaves participants holding locks indefinitely if coordinator fails mid-flight.',
  },
];

/** Seed question bank for adaptive testing across multiple skill areas */
export const seedAdaptiveQuestionBank: SeedFn = async (client: PoolClient, _size: SeedSize) => {
  console.log('  → Seeding question bank for adaptive testing...');

  let count = 0;
  for (const q of QUESTIONS) {
    await client.query(
      `INSERT INTO question_bank (
        skill_area, topic, difficulty, question_text, options, correct_answer, explanation, created_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())`,
      [
        q.skill_area,
        q.topic,
        q.difficulty,
        q.question_text,
        JSON.stringify(q.options),
        q.correct_answer,
        q.explanation,
      ]
    );
    count++;
  }

  console.log(`  ✓ Seeded ${count} questions across 3 skill areas in question_bank`);
};
