packages:
  - '.'

allowBuilds:
  '@apollo/protobufjs': true
  '@firebase/util': true
  '@scarf/scarf': true
  '@sentry-internal/node-cpu-profiler': true
  cpu-features: true
  'msgpackr-extract': true
  'protobufjs': true
  puppeteer: set this to true or false
  'sharp': true
  ssh2: true
