sonar.projectKey=mentorminds-backend
sonar.projectName=MentorsMind-Backend
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src,tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/coverage-e2e/**,**/*.config.ts,**/*.config.js,**/database/migrations/**
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-e2e/lcov.info
sonar.eslint.reportPaths=eslint-report.json
