/**
 * Machine-readable error codes for API responses.
 * Used by clients to programmatically handle specific error conditions.
 * Each code maps to a unique error scenario and is language/locale-independent.
 *
 * Structure: [DOMAIN]_[RESOURCE]_[CONDITION]
 * Example: BOOKING_CONFLICT, AUTH_INVALID_CREDENTIALS
 */

// Authentication & Authorization
export const AUTH_CODES = {
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  FORBIDDEN: "AUTH_FORBIDDEN",
  MISSING_CREDENTIALS: "AUTH_MISSING_CREDENTIALS",
  INSUFFICIENT_PERMISSIONS: "AUTH_INSUFFICIENT_PERMISSIONS",
  ACCOUNT_BANNED: "AUTH_ACCOUNT_BANNED",
  ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
} as const;

// Resource Not Found
export const NOT_FOUND_CODES = {
  USER_NOT_FOUND: "NOT_FOUND_USER",
  MENTOR_NOT_FOUND: "NOT_FOUND_MENTOR",
  MENTEE_NOT_FOUND: "NOT_FOUND_MENTEE",
  BOOKING_NOT_FOUND: "NOT_FOUND_BOOKING",
  SESSION_NOT_FOUND: "NOT_FOUND_SESSION",
  PAYMENT_NOT_FOUND: "NOT_FOUND_PAYMENT",
  WALLET_NOT_FOUND: "NOT_FOUND_WALLET",
  LEARNING_PATH_NOT_FOUND: "NOT_FOUND_LEARNING_PATH",
  MILESTONE_NOT_FOUND: "NOT_FOUND_MILESTONE",
  FORUM_NOT_FOUND: "NOT_FOUND_FORUM",
  WEBHOOK_NOT_FOUND: "NOT_FOUND_WEBHOOK",
  RECORDING_NOT_FOUND: "NOT_FOUND_RECORDING",
  VERIFICATION_NOT_FOUND: "NOT_FOUND_VERIFICATION",
  ENROLLMENT_NOT_FOUND: "NOT_FOUND_ENROLLMENT",
  SKILL_TEST_NOT_FOUND: "NOT_FOUND_SKILL_TEST",
  REVIEW_NOT_FOUND: "NOT_FOUND_REVIEW",
} as const;

// Booking-related errors
export const BOOKING_CODES = {
  ALREADY_PAID: "BOOKING_ALREADY_PAID",
  ALREADY_CONFIRMED: "BOOKING_ALREADY_CONFIRMED",
  ALREADY_CANCELLED: "BOOKING_ALREADY_CANCELLED",
  CONFLICT: "BOOKING_CONFLICT", // Mentor unavailable at requested time
  CONFLICT_TIME_OVERLAP: "BOOKING_CONFLICT_TIME_OVERLAP",
  MENTOR_UNAVAILABLE: "BOOKING_MENTOR_UNAVAILABLE",
  MENTEE_UNAVAILABLE: "BOOKING_MENTEE_UNAVAILABLE",
  INVALID_TIME_RANGE: "BOOKING_INVALID_TIME_RANGE",
  INVALID_STATE_TRANSITION: "BOOKING_INVALID_STATE_TRANSITION",
  INSUFFICIENT_BALANCE: "BOOKING_INSUFFICIENT_BALANCE",
  RATE_UNAVAILABLE: "BOOKING_RATE_UNAVAILABLE",
} as const;

// Payment & Wallet errors
export const PAYMENT_CODES = {
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_ALREADY_PROCESSED: "PAYMENT_ALREADY_PROCESSED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  INSUFFICIENT_FUNDS: "PAYMENT_INSUFFICIENT_FUNDS",
  UNSUPPORTED_CURRENCY: "PAYMENT_UNSUPPORTED_CURRENCY",
  UNSUPPORTED_ASSET: "PAYMENT_UNSUPPORTED_ASSET",
  INVALID_AMOUNT: "PAYMENT_INVALID_AMOUNT",
  QUOTE_EXPIRED: "PAYMENT_QUOTE_EXPIRED",
  QUOTE_NOT_FOUND: "PAYMENT_QUOTE_NOT_FOUND",
  TRANSACTION_FAILED: "PAYMENT_TRANSACTION_FAILED",
  ESCROW_RELEASE_FAILED: "PAYMENT_ESCROW_RELEASE_FAILED",
  INSUFFICIENT_ESCROW_BALANCE: "PAYMENT_INSUFFICIENT_ESCROW_BALANCE",
} as const;

// Input Validation errors
export const VALIDATION_CODES = {
  INVALID_INPUT: "VALIDATION_INVALID_INPUT",
  INVALID_EMAIL: "VALIDATION_INVALID_EMAIL",
  INVALID_PASSWORD: "VALIDATION_INVALID_PASSWORD",
  INVALID_TIMEZONE: "VALIDATION_INVALID_TIMEZONE",
  INVALID_DATE_RANGE: "VALIDATION_INVALID_DATE_RANGE",
  INVALID_CURSOR: "VALIDATION_INVALID_CURSOR",
  MISSING_REQUIRED_FIELD: "VALIDATION_MISSING_REQUIRED_FIELD",
  INVALID_UUID: "VALIDATION_INVALID_UUID",
  INVALID_ENUM_VALUE: "VALIDATION_INVALID_ENUM_VALUE",
} as const;

// Business Logic errors
export const BUSINESS_CODES = {
  DUPLICATE_ENTRY: "BUSINESS_DUPLICATE_ENTRY",
  DUPLICATE_REVIEW: "BUSINESS_DUPLICATE_REVIEW",
  DUPLICATE_ENROLLMENT: "BUSINESS_DUPLICATE_ENROLLMENT",
  ALREADY_COMPLETED: "BUSINESS_ALREADY_COMPLETED",
  STEP_ALREADY_COMPLETED: "BUSINESS_STEP_ALREADY_COMPLETED",
  NOT_ACTIVE: "BUSINESS_NOT_ACTIVE",
  NOT_PUBLISHED: "BUSINESS_NOT_PUBLISHED",
  IS_NOT_A_MENTOR: "BUSINESS_IS_NOT_A_MENTOR",
  ACCESS_DENIED: "BUSINESS_ACCESS_DENIED",
  PREREQUISITES_NOT_MET: "BUSINESS_PREREQUISITES_NOT_MET",
  INVALID_STATE: "BUSINESS_INVALID_STATE",
  IN_PROGRESS: "BUSINESS_IN_PROGRESS",
  LINK_EXISTS: "BUSINESS_LINK_EXISTS",
} as const;

// Rate limiting & Throttling
export const RATE_LIMIT_CODES = {
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  TOO_MANY_REQUESTS: "RATE_LIMIT_TOO_MANY_REQUESTS",
} as const;

// External Service errors
export const SERVICE_CODES = {
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  CIRCUIT_BREAKER_OPEN: "SERVICE_CIRCUIT_BREAKER_OPEN",
  TIMEOUT: "SERVICE_TIMEOUT",
  EXTERNAL_API_ERROR: "SERVICE_EXTERNAL_API_ERROR",
  DATABASE_ERROR: "SERVICE_DATABASE_ERROR",
  REDIS_ERROR: "SERVICE_REDIS_ERROR",
  SENDGRID_ERROR: "SERVICE_SENDGRID_ERROR",
  OPENAI_ERROR: "SERVICE_OPENAI_ERROR",
  ANTHROPIC_ERROR: "SERVICE_ANTHROPIC_ERROR",
  MEETING_PROVIDER_ERROR: "SERVICE_MEETING_PROVIDER_ERROR",
  CALENDAR_SYNC_ERROR: "SERVICE_CALENDAR_SYNC_ERROR",
} as const;

// Server errors
export const SERVER_CODES = {
  INTERNAL_ERROR: "SERVER_INTERNAL_ERROR",
  NOT_IMPLEMENTED: "SERVER_NOT_IMPLEMENTED",
  NOT_FOUND: "SERVER_NOT_FOUND",
  METHOD_NOT_ALLOWED: "SERVER_METHOD_NOT_ALLOWED",
} as const;

// Configuration errors
export const CONFIG_CODES = {
  MISSING_CONFIG: "CONFIG_MISSING_CONFIG",
  INVALID_CONFIG: "CONFIG_INVALID_CONFIG",
} as const;

/**
 * Consolidated mapping of all error codes
 */
export const ALL_ERROR_CODES = {
  ...AUTH_CODES,
  ...NOT_FOUND_CODES,
  ...BOOKING_CODES,
  ...PAYMENT_CODES,
  ...VALIDATION_CODES,
  ...BUSINESS_CODES,
  ...RATE_LIMIT_CODES,
  ...SERVICE_CODES,
  ...SERVER_CODES,
  ...CONFIG_CODES,
} as const;

export type ErrorCode = (typeof ALL_ERROR_CODES)[keyof typeof ALL_ERROR_CODES];

/**
 * Map error codes to HTTP status codes
 */
export const ERROR_CODE_TO_STATUS: Record<ErrorCode, number> = {
  // 400 - Bad Request
  [VALIDATION_CODES.INVALID_INPUT]: 400,
  [VALIDATION_CODES.INVALID_EMAIL]: 400,
  [VALIDATION_CODES.INVALID_PASSWORD]: 400,
  [VALIDATION_CODES.INVALID_TIMEZONE]: 400,
  [VALIDATION_CODES.INVALID_DATE_RANGE]: 400,
  [VALIDATION_CODES.INVALID_CURSOR]: 400,
  [VALIDATION_CODES.MISSING_REQUIRED_FIELD]: 400,
  [VALIDATION_CODES.INVALID_UUID]: 400,
  [VALIDATION_CODES.INVALID_ENUM_VALUE]: 400,
  [PAYMENT_CODES.INVALID_AMOUNT]: 400,
  [BOOKING_CODES.INVALID_TIME_RANGE]: 400,
  [BUSINESS_CODES.INVALID_STATE]: 400,
  [BUSINESS_CODES.NOT_PUBLISHED]: 400,
  [BUSINESS_CODES.IS_NOT_A_MENTOR]: 400,
  [AUTH_CODES.MISSING_CREDENTIALS]: 400,

  // 401 - Unauthorized
  [AUTH_CODES.INVALID_CREDENTIALS]: 401,
  [AUTH_CODES.TOKEN_EXPIRED]: 401,
  [AUTH_CODES.TOKEN_INVALID]: 401,
  [AUTH_CODES.UNAUTHORIZED]: 401,

  // 403 - Forbidden
  [AUTH_CODES.FORBIDDEN]: 403,
  [AUTH_CODES.INSUFFICIENT_PERMISSIONS]: 403,
  [AUTH_CODES.ACCOUNT_BANNED]: 403,
  [AUTH_CODES.ACCOUNT_SUSPENDED]: 403,
  [BUSINESS_CODES.ACCESS_DENIED]: 403,
  [BUSINESS_CODES.PREREQUISITES_NOT_MET]: 403,

  // 404 - Not Found
  [NOT_FOUND_CODES.USER_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.MENTOR_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.MENTEE_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.BOOKING_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.SESSION_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.PAYMENT_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.WALLET_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.LEARNING_PATH_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.MILESTONE_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.FORUM_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.WEBHOOK_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.RECORDING_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.VERIFICATION_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.ENROLLMENT_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.SKILL_TEST_NOT_FOUND]: 404,
  [NOT_FOUND_CODES.REVIEW_NOT_FOUND]: 404,
  [SERVER_CODES.NOT_FOUND]: 404,

  // 409 - Conflict
  [BOOKING_CODES.CONFLICT]: 409,
  [BOOKING_CODES.CONFLICT_TIME_OVERLAP]: 409,
  [BOOKING_CODES.MENTOR_UNAVAILABLE]: 409,
  [BOOKING_CODES.MENTEE_UNAVAILABLE]: 409,
  [BOOKING_CODES.ALREADY_PAID]: 409,
  [BOOKING_CODES.ALREADY_CONFIRMED]: 409,
  [BOOKING_CODES.ALREADY_CANCELLED]: 409,
  [BOOKING_CODES.INVALID_STATE_TRANSITION]: 409,
  [BUSINESS_CODES.DUPLICATE_ENTRY]: 409,
  [BUSINESS_CODES.DUPLICATE_REVIEW]: 409,
  [BUSINESS_CODES.DUPLICATE_ENROLLMENT]: 409,
  [BUSINESS_CODES.ALREADY_COMPLETED]: 409,
  [BUSINESS_CODES.STEP_ALREADY_COMPLETED]: 409,
  [BUSINESS_CODES.LINK_EXISTS]: 409,
  [PAYMENT_CODES.PAYMENT_ALREADY_PROCESSED]: 409,

  // 429 - Too Many Requests
  [RATE_LIMIT_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [RATE_LIMIT_CODES.TOO_MANY_REQUESTS]: 429,

  // 500 - Internal Server Error
  [BUSINESS_CODES.IN_PROGRESS]: 500,
  [BUSINESS_CODES.NOT_ACTIVE]: 500,
  [PAYMENT_CODES.PAYMENT_FAILED]: 500,
  [PAYMENT_CODES.PAYMENT_PENDING]: 500,
  [PAYMENT_CODES.TRANSACTION_FAILED]: 500,
  [PAYMENT_CODES.ESCROW_RELEASE_FAILED]: 500,
  [PAYMENT_CODES.UNSUPPORTED_CURRENCY]: 500,
  [PAYMENT_CODES.UNSUPPORTED_ASSET]: 500,
  [PAYMENT_CODES.QUOTE_NOT_FOUND]: 500,
  [PAYMENT_CODES.INSUFFICIENT_FUNDS]: 500,
  [PAYMENT_CODES.INSUFFICIENT_ESCROW_BALANCE]: 500,
  [BOOKING_CODES.INSUFFICIENT_BALANCE]: 500,
  [BOOKING_CODES.RATE_UNAVAILABLE]: 500,
  [SERVICE_CODES.DATABASE_ERROR]: 500,
  [SERVICE_CODES.REDIS_ERROR]: 500,
  [SERVICE_CODES.SENDGRID_ERROR]: 500,
  [SERVICE_CODES.OPENAI_ERROR]: 500,
  [SERVICE_CODES.ANTHROPIC_ERROR]: 500,
  [SERVICE_CODES.MEETING_PROVIDER_ERROR]: 500,
  [SERVICE_CODES.CALENDAR_SYNC_ERROR]: 500,
  [SERVICE_CODES.EXTERNAL_API_ERROR]: 500,
  [SERVER_CODES.INTERNAL_ERROR]: 500,
  [CONFIG_CODES.MISSING_CONFIG]: 500,
  [CONFIG_CODES.INVALID_CONFIG]: 500,

  // 502 - Bad Gateway
  [SERVICE_CODES.SERVICE_UNAVAILABLE]: 502,
  [SERVICE_CODES.CIRCUIT_BREAKER_OPEN]: 502,

  // 503 - Service Unavailable
  [SERVICE_CODES.TIMEOUT]: 503,

  // 501 - Not Implemented
  [SERVER_CODES.NOT_IMPLEMENTED]: 501,

  // 405 - Method Not Allowed
  [SERVER_CODES.METHOD_NOT_ALLOWED]: 405,
};

/**
 * Human-readable error messages (default English).
 * Should be replaced with i18n translations in production.
 */
export const ERROR_CODE_MESSAGES: Record<ErrorCode, string> = {
  // Auth
  [AUTH_CODES.INVALID_CREDENTIALS]: "Invalid email or password",
  [AUTH_CODES.TOKEN_EXPIRED]: "Token has expired",
  [AUTH_CODES.TOKEN_INVALID]: "Invalid token",
  [AUTH_CODES.UNAUTHORIZED]: "Unauthorized",
  [AUTH_CODES.FORBIDDEN]: "You do not have permission to access this resource",
  [AUTH_CODES.MISSING_CREDENTIALS]: "Credentials are required",
  [AUTH_CODES.INSUFFICIENT_PERMISSIONS]: "Insufficient permissions",
  [AUTH_CODES.ACCOUNT_BANNED]: "Your account has been permanently banned",
  [AUTH_CODES.ACCOUNT_SUSPENDED]: "Your account has been suspended",

  // Not Found
  [NOT_FOUND_CODES.USER_NOT_FOUND]: "User not found",
  [NOT_FOUND_CODES.MENTOR_NOT_FOUND]: "Mentor not found",
  [NOT_FOUND_CODES.MENTEE_NOT_FOUND]: "Mentee not found",
  [NOT_FOUND_CODES.BOOKING_NOT_FOUND]: "Booking not found",
  [NOT_FOUND_CODES.SESSION_NOT_FOUND]: "Session not found",
  [NOT_FOUND_CODES.PAYMENT_NOT_FOUND]: "Payment not found",
  [NOT_FOUND_CODES.WALLET_NOT_FOUND]: "Wallet not found",
  [NOT_FOUND_CODES.LEARNING_PATH_NOT_FOUND]: "Learning path not found",
  [NOT_FOUND_CODES.MILESTONE_NOT_FOUND]: "Milestone not found",
  [NOT_FOUND_CODES.FORUM_NOT_FOUND]: "Forum not found",
  [NOT_FOUND_CODES.WEBHOOK_NOT_FOUND]: "Webhook not found",
  [NOT_FOUND_CODES.RECORDING_NOT_FOUND]: "Recording not found",
  [NOT_FOUND_CODES.VERIFICATION_NOT_FOUND]: "Verification not found",
  [NOT_FOUND_CODES.ENROLLMENT_NOT_FOUND]: "Enrollment not found",
  [NOT_FOUND_CODES.SKILL_TEST_NOT_FOUND]: "Skill test not found",
  [NOT_FOUND_CODES.REVIEW_NOT_FOUND]: "Review not found",

  // Booking
  [BOOKING_CODES.ALREADY_PAID]: "Booking is already paid",
  [BOOKING_CODES.ALREADY_CONFIRMED]: "Booking is already confirmed",
  [BOOKING_CODES.ALREADY_CANCELLED]: "Booking is already cancelled",
  [BOOKING_CODES.CONFLICT]: "Booking conflict: Mentor is not available at the requested time",
  [BOOKING_CODES.CONFLICT_TIME_OVERLAP]: "Time slot conflicts with an existing booking",
  [BOOKING_CODES.MENTOR_UNAVAILABLE]: "Mentor is not available at the requested time",
  [BOOKING_CODES.MENTEE_UNAVAILABLE]: "You are not available at the requested time",
  [BOOKING_CODES.INVALID_TIME_RANGE]: "Invalid time range",
  [BOOKING_CODES.INVALID_STATE_TRANSITION]: "Invalid booking state transition",
  [BOOKING_CODES.INSUFFICIENT_BALANCE]: "Insufficient wallet balance",
  [BOOKING_CODES.RATE_UNAVAILABLE]: "Rate information unavailable",

  // Payment
  [PAYMENT_CODES.PAYMENT_FAILED]: "Payment failed",
  [PAYMENT_CODES.PAYMENT_ALREADY_PROCESSED]: "Payment has already been processed",
  [PAYMENT_CODES.PAYMENT_PENDING]: "Payment is pending",
  [PAYMENT_CODES.INSUFFICIENT_FUNDS]: "Insufficient funds",
  [PAYMENT_CODES.UNSUPPORTED_CURRENCY]: "Unsupported currency",
  [PAYMENT_CODES.UNSUPPORTED_ASSET]: "Unsupported asset",
  [PAYMENT_CODES.INVALID_AMOUNT]: "Invalid amount",
  [PAYMENT_CODES.QUOTE_EXPIRED]: "Quote has expired",
  [PAYMENT_CODES.QUOTE_NOT_FOUND]: "Quote not found",
  [PAYMENT_CODES.TRANSACTION_FAILED]: "Transaction failed",
  [PAYMENT_CODES.ESCROW_RELEASE_FAILED]: "Failed to release escrow",
  [PAYMENT_CODES.INSUFFICIENT_ESCROW_BALANCE]: "Insufficient escrow balance",

  // Validation
  [VALIDATION_CODES.INVALID_INPUT]: "Invalid input",
  [VALIDATION_CODES.INVALID_EMAIL]: "Invalid email address",
  [VALIDATION_CODES.INVALID_PASSWORD]: "Invalid password",
  [VALIDATION_CODES.INVALID_TIMEZONE]: "Invalid timezone",
  [VALIDATION_CODES.INVALID_DATE_RANGE]: "Invalid date range",
  [VALIDATION_CODES.INVALID_CURSOR]: "Invalid cursor",
  [VALIDATION_CODES.MISSING_REQUIRED_FIELD]: "Required field is missing",
  [VALIDATION_CODES.INVALID_UUID]: "Invalid UUID format",
  [VALIDATION_CODES.INVALID_ENUM_VALUE]: "Invalid enum value",

  // Business
  [BUSINESS_CODES.DUPLICATE_ENTRY]: "Duplicate entry",
  [BUSINESS_CODES.DUPLICATE_REVIEW]: "A review already exists for this session",
  [BUSINESS_CODES.DUPLICATE_ENROLLMENT]: "You are already enrolled in this learning path",
  [BUSINESS_CODES.ALREADY_COMPLETED]: "Already completed",
  [BUSINESS_CODES.STEP_ALREADY_COMPLETED]: "Step already completed",
  [BUSINESS_CODES.NOT_ACTIVE]: "Not active",
  [BUSINESS_CODES.NOT_PUBLISHED]: "Learning path is not published",
  [BUSINESS_CODES.IS_NOT_A_MENTOR]: "User is not a mentor",
  [BUSINESS_CODES.ACCESS_DENIED]: "Access denied",
  [BUSINESS_CODES.PREREQUISITES_NOT_MET]: "Prerequisites not met",
  [BUSINESS_CODES.INVALID_STATE]: "Invalid state",
  [BUSINESS_CODES.IN_PROGRESS]: "Operation in progress",
  [BUSINESS_CODES.LINK_EXISTS]: "Link already exists",

  // Rate Limiting
  [RATE_LIMIT_CODES.RATE_LIMIT_EXCEEDED]: "Rate limit exceeded",
  [RATE_LIMIT_CODES.TOO_MANY_REQUESTS]: "Too many requests",

  // Service
  [SERVICE_CODES.SERVICE_UNAVAILABLE]: "Service temporarily unavailable",
  [SERVICE_CODES.CIRCUIT_BREAKER_OPEN]: "Service temporarily unavailable (circuit breaker open)",
  [SERVICE_CODES.TIMEOUT]: "Request timeout",
  [SERVICE_CODES.EXTERNAL_API_ERROR]: "External service error",
  [SERVICE_CODES.DATABASE_ERROR]: "Database error",
  [SERVICE_CODES.REDIS_ERROR]: "Cache service error",
  [SERVICE_CODES.SENDGRID_ERROR]: "Email service error",
  [SERVICE_CODES.OPENAI_ERROR]: "AI service error",
  [SERVICE_CODES.ANTHROPIC_ERROR]: "AI service error",
  [SERVICE_CODES.MEETING_PROVIDER_ERROR]: "Meeting provider error",
  [SERVICE_CODES.CALENDAR_SYNC_ERROR]: "Calendar sync error",

  // Server
  [SERVER_CODES.INTERNAL_ERROR]: "Internal server error",
  [SERVER_CODES.NOT_IMPLEMENTED]: "Not implemented",
  [SERVER_CODES.NOT_FOUND]: "Not found",
  [SERVER_CODES.METHOD_NOT_ALLOWED]: "Method not allowed",

  // Config
  [CONFIG_CODES.MISSING_CONFIG]: "Missing configuration",
  [CONFIG_CODES.INVALID_CONFIG]: "Invalid configuration",
};
